# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200)),
                ('character_id', models.IntegerField(default=0)),
                ('activity', models.IntegerField(default=0)),
            ],
        ),
    ]
